# Generated by Django 4.0.5 on 2022-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('cosmetic', 'Cosmetic')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=15),
        ),
    ]
