# Generated by Django 4.0.5 on 2022-06-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_issue_severity_alter_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
