# Generated by Django 4.0.5 on 2022-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount_holding',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
