# Generated by Django 4.0.5 on 2022-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_portfolio_amount_holding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount_holding',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_symbol',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
