# Generated by Django 4.0.5 on 2022-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_portfolio_amount_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount_holding',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_name',
            field=models.CharField(default='United States Dollar', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='token_symbol',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
