# Generated by Django 4.0.5 on 2022-07-15 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_portfolio_amount_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('description', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
