# Generated by Django 4.0.5 on 2022-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='description',
            field=models.TextField(),
        ),
    ]
