# Generated by Django 4.0.5 on 2022-07-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_recruiter_company_alter_recruiter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
