# Generated by Django 4.0.5 on 2022-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_recruiter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='job_title',
            field=models.CharField(default='Big Wig', max_length=100),
            preserve_default=False,
        ),
    ]
